name: Create and Upload Artifact

on:
  workflow_call:

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a text file with "Hello World"
        run: echo "Hello World" > hello.txt

      - name: Upload hello.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-file
          path: hello.txt
