name: Download and Verify Artifact

on:
  workflow_call:

jobs:
  verify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from previous workflow
        uses: actions/download-artifact@v3
        with:
          name: hello-world-file
          path: ./artifact

      - name: Check if the file exists
        run: |
          if [ ! -f ./artifact/hello.txt ]; then
            echo "File not found!"
            exit 1
          fi

      - name: Verify file contents
        run: |
          FILE_CONTENT=$(cat ./artifact/hello.txt)
          if [ "$FILE_CONTENT" != "Hello World" ]; then
            echo "File contents do not match!"
            exit 1
          else
            echo "File contents verified successfully: $FILE_CONTENT"
          fi
