name: Full Deployment
on:
  repository_dispatch:
    types: [full_deploy]

concurrency:
  group: ci-full_deploy-runner
  cancel-in-progress: true

jobs:
  test-main:
    name: Test
    uses: ./.github/workflows/main.yaml