name: Full Deployment
on:
  repository_dispatch:
    types: [test_workflows]

concurrency:
  group: ci-test_workflows-runner
  cancel-in-progress: true

jobs:
  test-create:
    name: Create
    uses: ./.github/workflows/create-upload.yaml
  test-verify:
    needs: test-create
    name: Test
    uses: ./.github/workflows/download-verify.yaml