name: Windows Deploy
on:
  repository_dispatch:
    types: [deploy_windows]
  workflow_call:

env:
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes d3d12=yes "angle_libs=${{github.workspace}}/"
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  build-windows:
    runs-on: ubuntu-latest
    name: Building Editor for Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: blazium-engine/blazium
          ref: ${{ github.event.client_payload.branch }}

      - name: Set up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bash bzip2 curl file findutils gettext git make nano patch pkg-config python3-pip unzip xz-utils \
            dotnet-sdk-8.0
          pip install scons==4.8.0

      - name: Build Project
        run: |
          # Your build steps go here
